name: CI
on:
  push:
    branches:
      - main
    tags:        
      - v*
jobs:

  test:
    name: Execute Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: npm install
    - run: npm install -g typescript
    - run: npx tsc
    - run: npm test
  push_to_registry:
    name: Push Docker Container
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ronalruiiz/devops-project:latest
  deploy:
    name: Deploy Server
    needs: [push_to_registry]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:    
        - uses: actions/checkout@v2
        - name: Executing remote  command
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            key: ${{secrets.PRIVATE_KEY}}
            script: |
                docker stop devops-project
                docker pull ronalruiiz/devops-project && docker run -d --name devops-project -p 3000:3000 ronalruiiz/devops-project

